#!/bin/bash
# Downloads terrain images from Pokopia Wiki CDN
BASE="https://pub-63d9fdd35f184b7c82eb49a6ebead636.r2.dev/items"
OUT="$(dirname "$0")/../terrain"

mkdir -p "$OUT"
echo "Downloading ${#ITEMS[@]} terrain images to $OUT..."

ITEMS=(
  "aerodactyl-fossil-body"
  "aerodactyl-fossil-head"
  "aerodactyl-fossil-left-wing"
  "aerodactyl-fossil-right-wing"
  "aerodactyl-fossil-tail"
  "afternoon-tea-set"
  "alarm-clock"
  "amaura-fossil"
  "antique-chair"
  "antique-closet"
  "arcade-machine"
  "arcanine-plushie"
  "arrow-sign"
  "aurorus-fossil-body"
  "aurorus-fossil-head"
  "aurorus-fossil-tail"
  "balloon"
  "bamboo-shoot-rock"
  "barrier-gate"
  "bass-drum"
  "bastiodon-fossil-body"
  "bastiodon-fossil-head"
  "bastiodon-fossil-tail"
  "bathtub"
  "beach-flower"
  "beach-umbrella"
  "bed"
  "berry-lamp"
  "berry-picnic-basket"
  "bicycle"
  "bonfire"
  "bookshelf"
  "boxing-machine"
  "bread-oven"
  "campfire"
  "canoe"
  "canvas"
  "cardboard-box"
  "cash-register"
  "cd-player"
  "cd-rack"
  "celebration-armor"
  "cement-pipe"
  "chair"
  "chansey-planter"
  "chocolate-cookie"
  "cleaning-set"
  "control-panel"
  "cool-electric-bass"
  "cool-electric-guitar"
  "cranidos-fossil"
  "crystal-ball"
  "curse-armor"
  "cute-bed"
  "cute-lamp"
  "cutting-board"
  "desk-lamp"
  "desktop-computer"
  "dig-tools"
  "display-stand"
  "dragonite-plushie"
  "dresser"
  "duckweed"
  "eerie-candle"
  "eevee-plushie"
  "face-cutout-board"
  "fancy-hedge"
  "fire-generator"
  "first-aid-kit"
  "fishing-rod"
  "flatbed-cart"
  "floor-switch"
  "folding-screen"
  "frying-pan"
  "furnace"
  "gaming-pc"
  "garden-lamp"
  "hand-cart"
  "hanging-scroll"
  "hash-brown"
  "hot-rock"
  "hot-spring"
  "humidifier"
  "ice-cream-soda"
  "inflatable-boat"
  "iron-pipe-stack"
  "jack-in-the-box"
  "knitting-set"
  "lab-set"
  "lantern"
  "laptop"
  "large-coconut-tree"
  "large-mirror"
  "large-table"
  "launch-tube"
  "lava"
  "lighting"
  "log-bed"
  "long-bench"
  "lost-item-large"
  "low-cabinet"
  "luxury-floor-lamp"
  "machamp-rock"
  "magazine-rack"
  "manhole-cover"
  "menu-board"
  "metal-barrel"
  "microscope"
  "microwave"
  "misc-cabinet"
  "moonlight-dance-statue"
  "moss"
  "mossy-rock"
  "muddy-water"
  "mug"
  "mushroom-lamp"
  "music-mat"
  "newspaper"
  "offering-stand"
  "partition"
  "party-cup"
  "party-plate"
  "pen-holder"
  "picnic-basket"
  "pier"
  "pikachu-plushie"
  "pink-grass"
  "pizza"
  "plain-lamp"
  "plain-table"
  "plated-food"
  "plushie"
  "pok-ball-bed"
  "pok-ball-lamp"
  "pok-ball-sofa"
  "pok-ball-table"
  "potted-plant"
  "professor-s-treasure"
  "raichu-sign"
  "rail-track"
  "rainy-float-bubble"
  "rampardos-fossil-body"
  "rampardos-fossil-head"
  "rampardos-fossil-tail"
  "red-grass"
  "research-paper"
  "resort-lamp"
  "ribbon-cake"
  "rock-flower"
  "round-table"
  "sand-bag"
  "sand-pile"
  "sandbag"
  "sandwich"
  "sandy-rock"
  "scaffolding"
  "shaved-ice"
  "shieldon-fossil"
  "ship-wheel"
  "sign"
  "simple-cushion"
  "single-flower-vase"
  "sink"
  "sky-island-flower"
  "slide"
  "speaker"
  "spotlight"
  "stage"
  "standing-microphone"
  "steel-beam"
  "stepping-stone"
  "stone-fireplace"
  "stove"
  "street-lamp"
  "stylish-pot"
  "sunny-float-bubble"
  "table"
  "tablet"
  "tangled-wires"
  "team-rocket-decoration"
  "thin-candle"
  "tire"
  "tire-hop"
  "tombstone"
  "torch"
  "toy"
  "traffic-cone"
  "trash-bag"
  "trash-can"
  "tree-stump"
  "triangle-tree"
  "tv"
  "tyrantrum-fossil-body"
  "tyrantrum-fossil-feet"
  "tyrantrum-fossil-head"
  "tyrantrum-fossil-tail"
  "tyrunt-fossil"
  "utility-pole"
  "vegetable-field"
  "vending-machine"
  "victreebel-vase"
  "wall-towel"
  "wardrobe"
  "washstand"
  "water-basin"
  "water-generator"
  "water-outlet"
  "waterfall"
  "watering-can"
  "whiteboard"
  "wind-generator"
  "withered-grass"
  "wooden-barrel"
  "wooden-crate"
  "wooden-nest-box"
  "wooden-path"
  "wooden-perch"
  "yellow-grass"
)

MISSING=0
DOWNLOADED=0
for slug in "${ITEMS[@]}"; do
  dest="$OUT/$slug.png"
  if [ -f "$dest" ]; then continue; fi

  # First attempt: with dashes
  code=$(curl -s -o "$dest" -w "%{http_code}" "$BASE/$slug.png")
  if [ "$code" = "200" ]; then
    DOWNLOADED=$((DOWNLOADED + 1))
    continue
  fi
  rm -f "$dest"

  # Retry: without dashes
  nodash="${slug//-/}"
  code=$(curl -s -o "$dest" -w "%{http_code}" "$BASE/$nodash.png")
  if [ "$code" = "200" ]; then
    mv "$dest" "$OUT/$slug.png"
    echo "FOUND (no-dash): $slug -> $nodash"
    DOWNLOADED=$((DOWNLOADED + 1))
  else
    rm -f "$dest"
    echo "MISSING: $slug"
    MISSING=$((MISSING + 1))
  fi
done

echo "Done! Downloaded: $DOWNLOADED, Missing: $MISSING"
echo "$(ls "$OUT"/*.png 2>/dev/null | wc -l) images total in $OUT"
