#!/bin/bash
# Downloads item images from Pokopia Wiki CDN
BASE="https://pub-63d9fdd35f184b7c82eb49a6ebead636.r2.dev/items"
OUT="$(dirname "$0")/items"

mkdir -p "$OUT"
echo "Downloading item images to $OUT..."

ITEMS=(
  "storage-box"
  "wall-storage-box"
  "big-storage-box"
  "plain-chest"
  "office-cabinet"
  "gaming-fridge"
  "poke-ball-chest"
  "berry-case"
  "antique-chest"
  "plain-closet"
  "office-locker"
  "antique-closet"
  "office-shelf"
  "polygonal-shelf"
  "straw-table"
  "log-table"
  "side-table"
  "garden-table"
  "wooden-table"
  "counter"
  "wall-mounted-table"
  "straw-chair"
  "log-chair"
  "office-chair"
  "garden-chair"
  "wooden-chair"
  "retro-sofa"
  "plain-sofa"
  "office-sofa"
  "antique-sofa"
  "luxury-sofa"
  "cute-sofa"
  "hammock"
  "plain-bed"
  "office-bed"
  "bunk-bed"
  "antique-bed"
  "luxury-bed"
  "cute-bed"
  "plain-lamp"
  "office-lamp"
  "antique-lamp"
  "luxury-lamp"
  "cute-lamp"
  "plain-rug"
  "office-rug"
  "antique-rug"
  "luxury-rug"
  "cute-rug"
  "straw-rug"
  "plain-curtain"
  "office-curtain"
  "antique-curtain"
  "luxury-curtain"
  "cute-curtain"
  "plain-wallpaper"
  "office-wallpaper"
  "antique-wallpaper"
  "luxury-wallpaper"
  "cute-wallpaper"
  "plain-flooring"
  "office-flooring"
  "antique-flooring"
  "luxury-flooring"
  "cute-flooring"
  "plain-door"
  "office-door"
  "antique-door"
  "luxury-door"
  "cute-door"
  "plain-window"
  "office-window"
  "antique-window"
  "luxury-window"
  "cute-window"
  "plain-fence"
  "office-fence"
  "antique-fence"
  "luxury-fence"
  "cute-fence"
  "plain-decoration"
  "office-decoration"
  "antique-decoration"
  "luxury-decoration"
  "cute-decoration"
  "plain-plant"
  "office-plant"
  "antique-plant"
  "luxury-plant"
  "cute-plant"
  "plain-clock"
  "office-clock"
  "antique-clock"
  "luxury-clock"
  "cute-clock"
  "wall-mirror"
  "large-mirror"
  "antique-dresser"
  "luxury-dresser"
  "cute-dresser"
  "wiggly-mirror"
  "flower-table"
  "flower-cushion"
  "camping-chair"
  "sleeping-bag"
)

MISSING=0
DOWNLOADED=0
for slug in "${ITEMS[@]}"; do
  dest="$OUT/$slug.png"
  if [ -f "$dest" ]; then continue; fi
  code=$(curl -s -o "$dest" -w "%{http_code}" "$BASE/$slug.png")
  if [ "$code" = "200" ]; then
    DOWNLOADED=$((DOWNLOADED + 1))
  else
    rm -f "$dest"
    echo "MISSING: $slug ($code)"
    MISSING=$((MISSING + 1))
  fi
done

echo "Done! Downloaded: $DOWNLOADED, Missing: $MISSING"
echo "$(ls "$OUT"/*.png 2>/dev/null | wc -l) images total in $OUT"
